# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    volumes:
      - type: bind
        source: ./src/db-setup
        target: /docker-entrypoint-initdb.d
    environment:
        - MYSQL_ROOT_PASSWORD=test
    restart: always
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080